name: panmixer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - bcftools
  - ortools
  - plink
  - pip
  - pip:
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
